//Generated by update_extensions.py. Do not edit. Edit update_extensions.py instead
#include "extensions/extensions.h"
#include "memory.h"

extern void *init_mc_clone();
extern void deinit_mc_clone(void *ext);

struct Extensions
{
    void *mc_clone;
};

void *initExtensions()
{
    Extensions *ext = NEW(Extensions);
    ((Extensions *)ext)->mc_clone = init_mc_clone();
    return ext;
}

void deinitExtensions(void *ext)
{
    deinit_mc_clone(((Extensions *)ext)->mc_clone);
    DELETE((Extensions *)ext);
}

void *get_mc_clone(void *exts)
{
    return ((Extensions *)exts)->mc_clone;
}

